[project]
name = "weight-calculator"
version = "0.1.0"
description = "Weight calculator application using pressure-based interpolation"
requires-python = ">=3.11"
dependencies = [
    "briefcase>=0.3.15",
    "toga>=0.4.9",
    "toga-core>=0.4.9",
    "numpy>=2.2.2",
    "pillow>=11.1.0",
]

[tool.briefcase]
project_name = "Weight Calculator"
bundle = "org.weightcalculator"
version = "0.1.0"
url = "https://github.com/rockman256s/Scales-"
license = "MIT license"
author = "rockman256s"

[tool.briefcase.app.weightcalculator]
formal_name = "Weight Calculator"
description = "Weight calculator using pressure-based interpolation"
sources = ['beeware_app.py']
test_sources = ['tests']

[tool.briefcase.app.weightcalculator.macOS]
requires = []

[tool.briefcase.app.weightcalculator.linux]
requires = []

[tool.briefcase.app.weightcalculator.android]
requires = []
supported_platforms = ["android"]
build_gradle_dependencies = [
    "androidx.appcompat:appcompat:1.6.1",
    "com.google.android.material:material:1.10.0",
]