[project]
name = "weight-calculator"
version = "0.1.0"
description = "Weight calculator application using pressure-based interpolation"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.2",
    "pandas>=2.2.3",
    "pillow>=11.1.0",
    "streamlit>=1.42.0",
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
