{pkgs}: {
  deps = [
    pkgs.libpng
    pkgs.gtk3
    pkgs.libffi
    pkgs.ncurses
    pkgs.xz
    pkgs.openjdk11
    pkgs.binutils
    pkgs.gcc
    pkgs.cairo
    pkgs.mtdev
    pkgs.libcxx
    pkgs.SDL2_ttf
    pkgs.SDL2_mixer
    pkgs.SDL2_image
    pkgs.SDL2
    pkgs.glibcLocales
    pkgs.zlib
    pkgs.tk
    pkgs.tcl
    pkgs.openjpeg
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.freetype
    pkgs.xsimd
    pkgs.pkg-config
    pkgs.libxcrypt
  ];
}
