{pkgs}: {
  deps = [
    pkgs.openjdk11_headless
    pkgs.gperf
    pkgs.flex
    pkgs.bison
    pkgs.glibc
    pkgs.flutter
    pkgs.gcc
    pkgs.gnumake
    pkgs.automake
    pkgs.autoconf
    pkgs.cmake
    pkgs.libtool
    pkgs.openssl
    pkgs.jdk
    pkgs.gradle
    pkgs.android-tools
    pkgs.buildozer
    pkgs.xsimd
    pkgs.gdk-pixbuf
    pkgs.pango
    pkgs.fontconfig
    pkgs.google-cloud-sdk
    pkgs.zlib
    pkgs.openjpeg
    pkgs.libxcrypt
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.tk
    pkgs.tcl
    pkgs.qhull
    pkgs.gtk3
    pkgs.gobject-introspection
    pkgs.ghostscript
    pkgs.freetype
    pkgs.ffmpeg-full
    pkgs.cairo
    pkgs.pkg-config
    pkgs.mtdev
    pkgs.libcxx
    pkgs.SDL2_ttf
    pkgs.SDL2_mixer
    pkgs.SDL2_image
    pkgs.SDL2
    pkgs.glibcLocales
  ];
}
